export const CHANGE_ACTIVE_ROUTE = 'CHANGE_ACTIVE_ROUTE';
export const CHANGE_ACTIVE_URL = 'CHANGE_ACTIVE_URL';
export const SET_CAPTURING_TIME = 'SET_CAPTURING_TIME';
export const SET_RECORDING_VIDEO = 'SET_RECORDING_VIDEO';