export const SET_USER = 'SET_USER';
export const SET_DRIVE_USER = 'SET_DRIVE_USER';
export const REMOVE_SLACK_USER = 'REMOVE_SLACK_USER';
export const REMOVE_DROP_BOX_USER = 'REMOVE_DROP_BOX_USER';
export const REMOVE_JIRA_USER = 'REMOVE_JIRA_USER';
export const REMOVE_TRELLO_USER = 'REMOVE_TRELLO_USER';
export const SET_TRELLO_USER = 'SET_TRELLO_USER';