---
kind: Service
apiVersion: v1
metadata:
    name: ever-rec-portal-prod
spec:
    selector:
        app: ever-rec-portal-prod
    ports:
        - name: web
          protocol: TCP
          port: 4200
          targetPort: 4200
---
kind: Service
apiVersion: v1
metadata:
    name: ever-rec-api-prod
spec:
    selector:
        app: ever-rec-api-prod
    ports:
        - name: web
          protocol: TCP
          port: 3000
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ever-rec-api-prod
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ever-rec-api-prod
    template:
        metadata:
            labels:
                app: ever-rec-api-prod
        spec:
            containers:
                - name: ever-rec-api-prod
                  image: ghcr.io/ever-co/ever-rec-api:latest
                  env:
                      - name: API_HOST
                        value: 0.0.0.0
                      - name: FIREBASE_API_KEY
                        value: '$FIREBASE_API_KEY'
                      - name: FIREBASE_AUTH_DOMAIN
                        value: '$FIREBASE_AUTH_DOMAIN'
                      - name: FIREBASE_DATABASE_URL
                        value: '$FIREBASE_DATABASE_URL'
                      - name: FIREBASE_PROJECT_ID
                        value: '$FIREBASE_PROJECT_ID'
                      - name: FIREBASE_STORAGE_BUCKET
                        value: '$FIREBASE_STORAGE_BUCKET'
                      - name: FIREBASE_MESSAGING_SENDER_ID
                        value: '$FIREBASE_MESSAGING_SENDER_ID'
                      - name: FIREBASE_APP_ID
                        value: '$FIREBASE_APP_ID'
                      - name: FIREBASE_MEASUREMENT_ID
                        value: '$FIREBASE_MEASUREMENT_ID'                      
                      - name: FIREBASE_ADMIN_PRIVATE_KEY
                        value: '$FIREBASE_ADMIN_PRIVATE_KEY'
                      - name: FIREBASE_ADMIN_CLIENT_EMAIL
                        value: '$FIREBASE_ADMIN_CLIENT_EMAIL'

                  ports:
                      - containerPort: 3000
                        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ever-rec-portal-prod
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ever-rec-portal-prod
    template:
        metadata:
            labels:
                app: ever-rec-portal-prod
        spec:
            containers:
                - name: ever-rec-portal-prod
                  image: ghcr.io/ever-co/ever-rec-portal:latest
                  env:
                      - name: DEMO
                        value: 'false'
                  ports:
                      - containerPort: 4200
                        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: https-redirect
spec:
    redirectScheme:
        permanent: true
        scheme: https
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ever-rec-portal-prod-ing
    namespace: default
    annotations:
         traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
         traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
spec:
    ingressClassName: traefik
    rules:
        - host: app.rec.so
          http:
              paths:
                  - backend:
                        service:
                            name: ever-rec-portal-prod
                            port:
                                number: 4200
                    path: /
                    pathType: Prefix
    tls:
        - hosts:
              - app.rec.so
          secretName: app.rec.so-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ever-rec-api-prod-ing
    namespace: default
    annotations:
         traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
         traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
spec:
    ingressClassName: traefik
    rules:
        - host: app.rec.so
          http:
              paths:
                  - backend:
                        service:
                            name: ever-rec-api-prod
                            port:
                                number: 3000
                    path: /
                    pathType: Prefix
    tls:
        - hosts:
              - app.rec.so
          secretName: app.rec.so-tls
