name: Build and Publish Docker Images Dev

on:
    push:
        branches: [develop]

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    ever-rec-api:
        runs-on: buildjet-8vcpu-ubuntu-2204

        environment: dev

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./.deploy/portal/Dockerfile
                  load: true
                  tags: |
                      ghcr.io/ever-co/ever-rec-api-dev:latest
                      everco/ever-rec-api-dev:latest
                      registry.digitalocean.com/ever/ever-rec-api-dev:latest                      
                  cache-from: type=registry,ref=everco/ever-rec-api-dev:latest
                  cache-to: type=inline
                  build-args: |
                      NODE_ENV=development
                      FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
                      FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
                      FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}
                      FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
                      FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
                      FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
                      FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
                      FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
                      # FIREBASE ADMIN
                      FIREBASE_ADMIN_PRIVATE_KEY=${{ secrets.FIREBASE_ADMIN_PRIVATE_KEY }}
                      FIREBASE_ADMIN_CLIENT_EMAIL=${{ secrets.FIREBASE_ADMIN_CLIENT_EMAIL }}

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push to Docker Hub Registry
              run: |
                  docker push everco/ever-rec-api-dev:latest

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 3600

            - name: Push to DigitalOcean Registry
              run: |
                  docker push registry.digitalocean.com/ever/ever-rec-api-dev:latest

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Push to Github Registry
              run: |
                  docker push ghcr.io/ever-co/ever-rec-api-dev:latest
