name: Build and Publish Docker Images Prod

on:
    push:
        branches: [main]

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}
    cancel-in-progress: true

jobs:
    ever-rec-portal:
        runs-on: buildjet-8vcpu-ubuntu-2204

        environment: prod

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./.deploy/portal/Dockerfile
                  load: true
                  tags: |
                      ghcr.io/ever-co/ever-rec-portal:latest
                      everco/ever-rec-portal:latest
                      registry.digitalocean.com/ever/ever-rec-portal:latest
                      ${{ secrets.CW_DOCKER_REGISTRY }}/ever-co/ever-rec-portal:latest
                  cache-from: type=registry,ref=everco/ever-rec-portal:latest
                  cache-to: type=inline
                  build-args: |
                      NEXT_PUBLIC_EXTENSION_NAME=${{ secrets.NEXT_PUBLIC_EXTENSION_NAME }}
                      NEXT_PUBLIC_EXTENSION_ID=${{ secrets.NEXT_PUBLIC_EXTENSION_ID }}
                      NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
                      NEXT_PUBLIC_EXTENTION_REDIRECT_URL=${{ secrets.NEXT_PUBLIC_EXTENTION_REDIRECT_URL }}
                      NEXT_PUBLIC_REBRANDLY_API_KEY=${{ secrets.NEXT_PUBLIC_REBRANDLY_API_KEY }}

                      NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
                      NEXT_PUBLIC_WEBSITE_URL=${{ secrets.NEXT_PUBLIC_WEBSITE_URL }}
                      NEXT_PUBLIC_STATIC_FILES_URL=${{ secrets.NEXT_PUBLIC_STATIC_FILES_URL }}

                      NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Push to Docker Hub Registry
              run: |
                  docker push everco/ever-rec-portal:latest

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 3600

            - name: Push to DigitalOcean Registry
              run: |
                  docker push registry.digitalocean.com/ever/ever-rec-portal:latest

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Push to Github Registry
              run: |
                  docker push ghcr.io/ever-co/ever-rec-portal:latest

            - name: Login to CW Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ secrets.CW_DOCKER_REGISTRY }}
                  username: ${{ secrets.CW_DOCKER_USER }}
                  password: ${{ secrets.CW_DOCKER_USER_PASSWORD }}

        #  - name: Push to CW Registry
        #    run: |
        #      docker push ${{ secrets.CW_DOCKER_REGISTRY }}/ever-co/ever-rec-portal:latest
